### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'title') 

### ISSUE THREAD

**Issue by Tetracyl** [Tetracyl/EarTensifier#214]
```14|EarTensifier  | [9/6/2022] [5:31:18 AM] [Shard 105] › ✖  error     TypeError: Cannot read properties of null (reading 'title') 
14|EarTensifier  |     at Skip.run (/home/seif/ear_tensifier/src/commands/music/Skip.js:26:44)
14|EarTensifier  |     at InteractionCreate.run (/home/seif/ear_tensifier/src/listeners/client/InteractionCreate.js:215:27)
14|EarTensifier  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)```

**Comment by Tetracyl** [comment]
```
14|EarTensifier  | [9/6/2022] [5:40:53 AM] [Shard 077] › ✖  error     TypeError: Cannot destructure property 'title' of 'player.queue.current' as it is null. 
14|EarTensifier  |     at NowPlaying.run (/home/seif/ear_tensifier/src/commands/music/NowPlaying.js:22:17)
14|EarTensifier  |     at InteractionCreate.run (/home/seif/ear_tensifier/src/listeners/client/InteractionCreate.js:215:27)
14|EarTensifier  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)```
