### ISSUE TITLE
Sharding error

### ISSUE THREAD

**Issue by SpalaXy** [Tetracyl/EarTensifier#251]
Hello, can u help me this problem ?

(node:2872) DeprecationWarning: MessageEmbed#addField is deprecated and will be removed in the next major update. Use MessageEmbed#addFields instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/home/runner/SpalaBot-or-500-cmds-3/src/interactions/Command/help.js:18
    run: async (client, interaction, args) => {
    ^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /home/runner/SpalaBot-or-500-cmds-3/src/handlers/loaders/commands.js:24:29
    at Array.forEach (<anonymous>)
/home/runner/SpalaBot-or-500-cmds-3/node_modules/discord.js/src/sharding/Shard.js:161
        reject(new Error('SHARDING_READY_DIED', this.id));
               ^

Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/runner/SpalaBot-or-500-cmds-3/node_modules/discord.js/src/sharding/Shard.js:161:16)
    at Object.onceWrapper (node:events:514:26)
    at Shard.emit (node:events:406:35)
    at Shard._handleExit (/home/runner/SpalaBot-or-500-cmds-3/node_modules/discord.js/src/sharding/Shard.js:407:10)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  [Symbol(code)]: 'SHARDING_READY_DIED'
}
exit status 1

**Comment by Meqativ** [comment]
this isn't the repository for spalabot or whatever...

**Comment by SpalaXy** [comment]
@Meqativ, SpalaBot is just the name of Bot..

**Comment by SpalaXy** [comment]
SpalaXy_ = SPALAxy_

SPALAbot = SPALAxy_

**Comment by Meqativ** [comment]
> @Meqativ, SpalaBot is just the name of Bot..
![Screenshot_20230611-224210_1](https://github.com/Tetracyl/EarTensifier/assets/106783764/07ff2f72-0bb4-4fdd-8293-ca7d12928388)
