### ISSUE TITLE
Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.

### ISSUE THREAD

**Issue by TheMickeyz** [Tetracyl/EarTensifier#78]
Excuse me, can u help me this problem?

Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (C:\Desktop\EarTensifier\node_modules\discord.js\src\sharding\Shard.js:158:16)
    at Object.onceWrapper (node:events:510:26)
    at Shard.emit (node:events:390:28)
    at Shard.emit (node:domain:475:12)
    at Shard._handleExit (C:\Desktop\EarTensifier\node_modules\discord.js\src\sharding\Shard.js:394:10)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
Emitted 'error' event on Shard instance at:
    at C:\Desktop\EarTensifier\node_modules\discord.js\src\sharding\Shard.js:402:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'SHARDING_READY_DIED'
}

**Comment by Shelbyakayoub** [comment]
can some one help me?
