### ISSUE TITLE
Error [CHANNEL_NOT_CACHED]: Could not find the channel where this message came from in the cache! 

### ISSUE THREAD

**Issue by Tetracyl** [Tetracyl/EarTensifier#83]
```
19|EarTensifier  | [12/15/2021] [2:15:04 AM] [Shard 00] › ✖  error     Error [CHANNEL_NOT_CACHED]: Could not find the channel where this message came from in the cache! 
19|EarTensifier  |     at Message.edit (/home/seif/ear_tensifier/node_modules/discord.js/src/structures/Message.js:653:46)
19|EarTensifier  |     at Timeout._onTimeout (/home/seif/ear_tensifier/src/listeners/player/TrackStart.js:67:72)
19|EarTensifier  |     at listOnTimeout (node:internal/timers:557:17)
19|EarTensifier  |     at processTimers (node:internal/timers:500:7)```

**Comment by Meqativ** [comment]
no way
